// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz92HGCbZFTxJYEbsymeBaOHu-ImR_qXQ',
    appId: '1:981433400293:android:9d391a83422271de370d0c',
    messagingSenderId: '981433400293',
    projectId: 'test-flutter-project-41421',
    storageBucket: 'test-flutter-project-41421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANO4-bQaMj79qMneeC--s6VrNQ9XD99y4',
    appId: '1:981433400293:ios:e3ec8ce8cf77b806370d0c',
    messagingSenderId: '981433400293',
    projectId: 'test-flutter-project-41421',
    storageBucket: 'test-flutter-project-41421.firebasestorage.app',
    iosBundleId: 'com.example.testFirbaseProject',
  );
}